### ISSUE TITLE
Migrate DB

### ISSUE THREAD

**Issue by North-Hess** [North-Hess/StickyNotes#11]
Planetscale hobby plan will be gone April 8th. Migrate database to a different provider (turso)

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

**Comment by North-Hess** [comment]
@hooopo I appreciate the recommendation but I am already set on trying out Turso (recommended by Primeagen) because it has more storage and requests on a per month basis.
